sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t plux96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true plux96/react-test npm run test

after_success:
  - docker build -t plux96/multi-client ./client
  - docker build -t plux96/multi-nginx ./nginx
  - docker build -t plux96/multi-server ./server
  - docker build -t plux96/multi-worker ./worker
  # LOGIN docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and to push Docker Hub
  - docker push plux96/multi-client
  - docker push plux96/multi-nginx
  - docker push plux96/multi-server
  - docker push plux96/multi-worker
