sudo:required
language: generic
services:
  - docker

before_install:
  - docker build -t plux96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true plux96/react-test npm run test

after_success:
  - docker build -t plux96/multi-client ./client
  - docker build -t plux96/multi-nginx ./nginx
  - docker build -t plux96/multi-server ./server
  - docker build -t plux96/multi-worker ./worker
